version: '3.1'

services:
  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./build:/usr/share/nginx/html #TODO: ./build为本地映射
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - internal_network
  #   depends_on:
  #     - api
  #     - frontend
  #     - db
  #   command: /bin/bash -c "nginx -g 'daemon off;'"

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    # cap_add:
    #   - SYS_NICE
    restart: always
    volumes:
      - data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: treehust
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    networks:
      - internal_network
    expose:
      - 3306


  api:
    build: 
      context: backend
    # image: tree_hust_api
    restart: always
    ports:
      - "8000:8000"
      - "25:25"
    networks:
      - internal_network
    depends_on:
      - db
    expose:
      - 8000
    command: sh run.sh
    

  frontend:
    # build: 
    #   context: website
    image: tree_hust_frontend
    restart: always
    ports:
      - "3000:3000"
      - "80:80"
    networks:
      - internal_network
    depends_on:
      - api
    expose:
      - 3000


networks:
  internal_network: 


volumes:
  data:
    driver: local


